"""
Master URL list for NOMAD Survival Library.
All PDF sources compiled from:
- seasonedcitizenprepper.com (direct + Google Docs)
- trueprepper.com
- infobooks.org
"""

# Source: trueprepper.com
TRUEPREPPER_URLS = [
    {"url": "https://trueprepper.com/wp-content/uploads/2022/11/FM-21-76-US-Army-Survival-Manual.pdf", "title": "FM 21-76 US Army Survival Manual", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2023/03/FM-21-76-1-Survival-Evasion-and-Recovery-Multiservice-Procedures.pdf", "title": "FM 21-76-1 Survival Evasion and Recovery", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/12/FM-31-70-Basic-Cold-Weather-Manual.pdf", "title": "FM 31-70 Basic Cold Weather Manual", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/USMC-Summer-Survival-Course-Handbook.pdf", "title": "USMC Summer Survival Course Handbook", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/USMC-Winter-Survival-Course-Handbook.pdf", "title": "USMC Winter Survival Course Handbook", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/12/FM-3-06-Urban-Operations-FM-90-10-US-Army.pdf", "title": "FM 3-06 Urban Operations", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/FM-3-3-1-Nuclear-Contamination-Avoidance.pdf", "title": "FM 3-3-1 Nuclear Contamination Avoidance", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/FM-3-4-NBC-Protection.pdf", "title": "FM 3-4 NBC Protection", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/FM-3-5-NBC-Decontamination.pdf", "title": "FM 3-5 NBC Decontamination", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/FM-3-25-26-Map-Reading-and-Land-Navigation.pdf", "title": "FM 3-25.26 Map Reading and Land Navigation", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/FM-3-25-150-Combatives.pdf", "title": "FM 3-25.150 Combatives", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/FM-4-25-11-First_Aid.pdf", "title": "FM 4-25.11 First Aid", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/12/FM-5-103-Survivability.pdf", "title": "FM 5-103 Survivability", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/FM-20-3-Camouflage-Concealment-and-Decoys.pdf", "title": "FM 20-3 Camouflage Concealment and Decoys", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/FM-21-10-Field-Hygiene-and-Sanitation.pdf", "title": "FM 21-10 Field Hygiene and Sanitation", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/FMFRP-12-80-USMC-Kill-or-Get-Killed.pdf", "title": "FMFRP 12-80 USMC Kill or Get Killed", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/MA-1.02-USMC-Fundamentals-of-Martial-Arts.pdf", "title": "MA 1.02 USMC Fundamentals of Martial Arts", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/NAVMED-P-5010-US-Navy-Manual-of-Preventive-Medicine.pdf", "title": "NAVMED P-5010 USN Manual of Preventive Medicine", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/12/ST-31-91B-US-Army-Special-Forces-Medical-Handbook.pdf", "title": "ST 31-91B Special Forces Medical Handbook", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/STP-21-1-Army-Warrior-Skills-Level-1-Soldiers-Manual-of-Common-Tasks.pdf", "title": "STP 21-1 Army Warrior Skills Level 1", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/STP-21-24-Army-Warrior-Leader-Skills-Level-2-3-and-4.pdf", "title": "STP 21-24 Army Warrior Leader Skills Level 2-3-4", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/11/TM-31-210-Improvised-Munitions-Handbook.pdf", "title": "TM 31-210 Improvised Munitions Handbook", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Canadian-Military-Fieldcraft.pdf", "title": "Canadian Military Fieldcraft", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2023/03/Down-But-Not-Out-Canadian-Survival-Manual.pdf", "title": "Down But Not Out - Canadian Survival Manual", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/CIA-RDP78-Introdution-to-Survival.pdf", "title": "CIA Introduction to Survival", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Boy-Scout-Handbook-1911.pdf", "title": "Boy Scout Handbook 1911", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/US-Antarctic-Continental-Field-Manual.pdf", "title": "US Antarctic Continental Field Manual", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Canadian-Military-Basic-Cold-Weather-Training.pdf", "title": "Canadian Military Basic Cold Weather Training", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/12/Deadfalls-and-Snares.pdf", "title": "Deadfalls and Snares", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/12/Paleo-Pocalypse.pdf", "title": "Paleo-Pocalypse", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/12/Shelters-Shacks-and-Shanties.pdf", "title": "Shelters Shacks and Shanties", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/FEMA-Citizen-Preparedness-Guide.pdf", "title": "FEMA Citizen Preparedness Guide", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/12/LDS-Preparedness-Manual.pdf", "title": "LDS Preparedness Manual", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Be-Prepared-Estonia-Crisis-Guide-Paasteamet-ERB.pdf", "title": "Estonia Be Prepared Crisis Guide", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Norway-One-Week-Preparedness-Guide.pdf", "title": "Norway One Week Preparedness Guide", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Sweden-In-Case-of-Crisis-or-War.pdf", "title": "Sweden In Case of Crisis or War", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/11/Where-There-is-no-Doctor-a-Village-Health-Care-Handbook.pdf", "title": "Where There is No Doctor", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/12/Where-There-is-No-Dentist.pdf", "title": "Where There is No Dentist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/DTRA-Collateral-Damage-to-Satellites-from-an-EMP-Attack.pdf", "title": "Collateral Damage to Satellites from an EMP Attack", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/11/Nuclear-Winter-The-Anthropology-of-Human-Survival.pdf", "title": "Nuclear Winter - The Anthropology of Human Survival", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/09/Planning-Guidance-for-Response-to-Nuclear-Detonation-May-2022-FEMA.pdf", "title": "FEMA Planning Guide for Response to Nuclear Detonation", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/09/Nuclear-War-Survival-Skills-Cresson-Kearny.pdf", "title": "Nuclear War Survival Skills by Cresson Kearny", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2023/04/Family-Shelter-Designs-DOD-Civil-Defense.pdf", "title": "Family Shelter Designs - DOD Civil Defense", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2022/11/Build-a-Protective-Fallout-Shelter.pdf", "title": "Build a Protective Fallout Shelter", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Basic-Emergency-Plan.pdf", "title": "Basic Emergency Plan", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Home-Survival-Kit-Checklist-v2-2-Page-1.pdf", "title": "Home Survival Kit Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Survival-Food-Checklist-v2.pdf", "title": "Survival Food Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Everyday-Carry-Checklist-v3-2-Page.pdf", "title": "Everyday Carry Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Bug-Out-Bag-Checklist-v3-2-Page.pdf", "title": "Bug Out Bag Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Get-Home-Bag-Checklist-v3-2-Page.pdf", "title": "Get Home Bag Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/INCH-Bag-Checklist-v2-2-Page-1.pdf", "title": "INCH Bag Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/WUSH-Bag-Checklist-v3.pdf", "title": "WUSH Bag Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/SCARE-Bag-Checklist-v2.pdf", "title": "SCARE Kit Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Nuclear-Survival-Kit-Checklist-v3.pdf", "title": "Nuclear Survival Kit Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Flood-Survival-Kit-Checklist-v3.pdf", "title": "Flood Survival Kit Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Hurricane-Survival-Kit-Checklist.pdf", "title": "Hurricane Survival Kit Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Kids-Bug-Out-Bag-Checklist-v3.pdf", "title": "Kids Bug Out Bag Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Dog-Bug-Out-Bag-Checklist-v3.pdf", "title": "Dog Bug Out Bag Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Car-Emergency-Kit-Checklist-v3.pdf", "title": "Car Emergency Kit Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Bug-Out-Vehicle-Checklist-v3.pdf", "title": "Bug Out Vehicle Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/Survival-First-Aid-Kit-Checklist-v3.pdf", "title": "Survival First Aid Kit Checklist", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2023/01/Printable-PDF-of-the-Military-Phonetic-Alphabet.pdf", "title": "Military Phonetic Alphabet", "source": "trueprepper"},
    {"url": "https://trueprepper.com/wp-content/uploads/2023/01/Printable-PDF-of-the-Universal-Edibility-Test-for-Survival.pdf", "title": "Universal Edibility Test", "source": "trueprepper"},
]

# Source: infobooks.org
INFOBOOKS_URLS = [
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/1.-You-Alone-in-the-Maine-Woods-Author-Michael-F-Richard-Brad-Rounds-Bryan-Courtois.pdf", "title": "You Alone in the Maine Woods", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/3.-Survival-Author-Calvin-Crest.pdf", "title": "Survival - Calvin Crest", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/5.-Ultimate-Survival-Skills-Guide-Author-Joe-Marshall.pdf", "title": "Ultimate Survival Skills Guide", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/2.-Wilderness-Survival-Author-Survivor-Library.pdf", "title": "Wilderness Survival", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/4.-The-Elements-of-Surviving-Author-Saint-Paul-Public-Schools.pdf", "title": "The Elements of Surviving", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/6.-Survival-Author-Civil-Aviation-Authority-of-New-Zealand.pdf", "title": "Survival - Civil Aviation Authority NZ", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/8.-A-Long-Term-Survival-Guide-101-Ways-To-Start-A-Fire-Author-Survival-Ready-Blog.pdf", "title": "101 Ways To Start A Fire", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/9.-Survival-Skills-101-Author-Jason-Stevenson-Alison-Fromme.pdf", "title": "Survival Skills 101", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/10.-Winter-survival-in-the-backcountry-inter-survival-in-the-backcountry-Author-Albertas-Parks.pdf", "title": "Winter Survival in the Backcountry", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/12.-Burning-Man-Family-Survival-Guide-Author-Burning-Man.pdf", "title": "Burning Man Family Survival Guide", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/11.-How-to-use-a-compass-Author-Camp-Allatoona-Aquatics-Base.pdf", "title": "How to Use a Compass", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/14.-How-to-Go-Winter-Camping-and-Backpacking-Author-Heart-of-America-Council.pdf", "title": "How to Go Winter Camping and Backpacking", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/15.-Outback-Survival-Author-Gordon-Dedman.pdf", "title": "Outback Survival", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/North-American-Basic-Wilderness-Survival-Skills-Manual-Robert-Allen.pdf", "title": "North American Basic Wilderness Survival Skills Manual", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/Shelter-Construction-Techniques-for-Moderate-Weather-Nick-Weighton.pdf", "title": "Shelter Construction Techniques for Moderate Weather", "source": "infobooks"},
    {"url": "https://pdf.infobooks.org//ING/382%20Survival/Shelter-Building-Designs-York-Ebor-District-Scouts.pdf", "title": "Shelter Building Designs", "source": "infobooks"},
]

# Source: seasonedcitizenprepper.com - Direct PDF links
SCP_DIRECT_URLS = [
    {"url": "http://kazvswild.com/wp-content/uploads/2015/04/composting-how-to-make-fertilizer.pdf", "title": "Composting - How to Make Fertilizer", "source": "scp"},
    {"url": "http://kazvswild.com/wp-content/uploads/2015/04/greenhouse-whitefly-control.pdf", "title": "Greenhouse Whitefly Control", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/11-Steps-to-Survival-Canada-Emergency-Measurses-Organization.pdf", "title": "11 Steps to Survival - Canada Emergency Measures", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/ABCs-of-nuclear-survival.pdf", "title": "ABCs of Nuclear Survival", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/Citizens-Homeland-Defense-Guide-II-The-Art-of-Survival.pdf", "title": "Citizens Homeland Defense Guide II", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/Citizens-Homeland-Defense-Guide-I-The-Art-of-Survival.pdf", "title": "Citizens Homeland Defense Guide I", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/Disaster_Supply_Kit.pdf", "title": "Disaster Supply Kit", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/Emergency-Plan.pdf", "title": "Emergency Plan", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/General_-_Becoming_Self-Sufficient_for_Six_Months.pdf", "title": "Becoming Self-Sufficient for Six Months", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/General_-_Compact_survival_kit.pdf", "title": "Compact Survival Kit", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/General_-_Dangerous_Animals.pdf", "title": "Dangerous Animals", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/General_-_PreparingForDisasterforPeopleWithDisabilities.pdf", "title": "Preparing for Disaster for People With Disabilities", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/General_-_Signaling_and_Direction_Finding.pdf", "title": "Signaling and Direction Finding", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/General_-_Social_Distancing_and_Pandemic_Readiness.pdf", "title": "Social Distancing and Pandemic Readiness", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/General_-_Strengthening_exterior_doors.pdf", "title": "Strengthening Exterior Doors", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/General_-_Surviving_in_the_City.pdf", "title": "Surviving in the City", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/Survive-Doomsday.pdf", "title": "Survive Doomsday", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/Tactical-Ready-Guide.pdf", "title": "Tactical Ready Guide", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/Test-The-Soil-First.pdf", "title": "Test The Soil First", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/The-Amateur-Garden.pdf", "title": "The Amateur Garden", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/The-Construction-of-Secret-Hiding-Placesreduced.pdf", "title": "The Construction of Secret Hiding Places", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/The-Effects-of-Nuclear-War.pdf", "title": "The Effects of Nuclear War", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/THE-INTERNATIONAL-CBRN-TRAINING.pdf", "title": "The International CBRN Training", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/The-Worst-Case-Scenario-Survival-Handbook.pdf", "title": "The Worst Case Scenario Survival Handbook", "source": "scp"},
    {"url": "http://ready4itall.org/wp-content/uploads/2013/05/TOP-120-CITIES-AT-RISK-FOR-NBC-ATTACK.pdf", "title": "Top 120 Cities at Risk for NBC Attack", "source": "scp"},
    {"url": "http://www.landsurvival.com/downloads/SAS%20Survival%20Handbook.pdf", "title": "SAS Survival Handbook", "source": "scp"},
    {"url": "http://www.survivorlibrary.com/library/the-ten-bushcraft-books.pdf", "title": "The Ten Bushcraft Books", "source": "scp"},
    {"url": "https://graywolfsurvival.com/wp-content/uploads/1881_Household_Cyclopedia.pdf", "title": "The 1881 Household Cyclopedia", "source": "scp"},
    {"url": "https://graywolfsurvival.com/wp-content/uploads/Canning_and_preserving_1912.pdf", "title": "Canning and Preserving 1912", "source": "scp"},
    {"url": "https://graywolfsurvival.com/wp-content/uploads/How-to-make-Black-Powder.pdf", "title": "How To Make Black Powder", "source": "scp"},
    {"url": "https://graywolfsurvival.com/wp-content/uploads/Physical-Security-FM-3-19.30.pdf", "title": "Physical Security FM 3-19.30", "source": "scp"},
    {"url": "https://graywolfsurvival.com/wp-content/uploads/Preservation_of_Fish_and_Meat_2004.pdf", "title": "Preservation of Fish and Meat", "source": "scp"},
    {"url": "https://graywolfsurvival.com/wp-content/uploads/Rural_Tanning_Techniques_No-68_1974.pdf", "title": "Rural Tanning Techniques", "source": "scp"},
    {"url": "https://graywolfsurvival.com/wp-content/uploads/The_Handbook_For_Practical_Farmers_1920.pdf", "title": "The Handbook For Practical Farmers 1920", "source": "scp"},
    {"url": "https://graywolfsurvival.com/wp-content/uploads/Tricks-of-Trapping.pdf", "title": "Tricks of Trapping", "source": "scp"},
    {"url": "https://graywolfsurvival.com/wp-content/uploads/USMC-Summer-Survival-Course-Handbook-_6_february-2005.pdf", "title": "USMC Summer Survival Course Handbook 2005", "source": "scp"},
    {"url": "https://graywolfsurvival.com/wp-content/uploads/Water_-_Water_Treatment.pdf", "title": "Water Treatment", "source": "scp"},
    {"url": "https://ia801406.us.archive.org/13/items/deadfallssnaresb00harduoft/deadfallssnaresb00harduoft.pdf", "title": "Deadfalls and Snares - AR Harding", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2012/05/sfhandbook.pdf", "title": "US Army Special Forces Medical Handbook ST 31-91B", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2012/06/ranger.pdf", "title": "Ranger Handbook 2006", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2012/10/LDSPrep-V8.pdf", "title": "LDS Preparedness Manual 2012", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2012/12/ARMY-Military-Mountaineering.pdf", "title": "Army FM 3-97 Military Mountaineering", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2012/12/canning.pdf", "title": "Canning Guide", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2012/12/wintersurvival.pdf", "title": "Montana Winter Survival Manual", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/01/Survival-and-Austere-Medicine.pdf", "title": "Survival and Austere Medicine", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/01/The-Guerrilla-and-How-to-Fight-Him.pdf", "title": "The Guerrilla and How to Fight Him", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/01/WoodBurning.pdf", "title": "Wood Burning", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/02/1881_Household_Cyclopedia.pdf", "title": "1881 Household Cyclopedia", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/02/Evers_SafetyBook_V3.pdf", "title": "How to Handle a Crisis", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/02/FM-21-76-1-Survival-Evasion-Recovery.pdf", "title": "FM 21-76-1 Survival Evasion Recovery", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/02/GUIDE-1-Home-Can.pdf", "title": "Complete Guide to Home Canning", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/03/Art-of-War-PDF-1.pdf", "title": "Art of War", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/03/checklist_1_72_hr._kit.pdf", "title": "FEMA Emergency Supplies Checklist", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/03/familylist1.pdf", "title": "FEMA Family Supply List", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/03/GeneratorLoadChart.pdf", "title": "Generator Load Chart", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/04/3_Day_Emergency_Prep_-_BOB_6.09_.pdf", "title": "3 Day Emergency Prep", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/04/Morel_Mushroom_Hunting_Tips-1.pdf", "title": "Morel Mushroom Hunting Tips", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/06/nuclearsurvivalskills.pdf", "title": "Nuclear War Survival Skills", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/08/MP-15.fam_.1959.pdf", "title": "The Family Fallout Shelter MP-15", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/09/Camping-Recipes.pdf", "title": "Camping Recipes", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/10/DutchOvenGrillBarBQrecipes.pdf", "title": "Dutch Oven and Grill Recipes", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/10/FEMA-nuclear-survival.pdf", "title": "FEMA Protection In The Nuclear Age", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/10/MoreJerky.pdf", "title": "Jerky Recipes", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2013/12/3monthsupplyoffoodschedule2.pdf", "title": "3 Month Food Supply Schedule", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2014/02/SODIS-manual.pdf", "title": "SODIS Safe Water School Training Manual", "source": "scp"},
    {"url": "https://seasonedcitizenprepper.com//wp-content/uploads/2014/09/60giftmixesjarrecipes.pdf", "title": "60 Gift Mixes In-A-Jar Recipes", "source": "scp"},
]

# Source: seasonedcitizenprepper.com - Google Docs links
SCP_GDOCS_URLS = [
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMTZiOGFmOGYtMzdiNC00NTA1LTk2MzgtMjExNmMyYzQ4MDM2", "title": "Army STP 21-1 Soldiers Manual Warrior Skills Level 1", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNTMyOThmYTYtMTUxOC00Y2U1LTk3NGItZmY5NTE1MjU2MzJh", "title": "Army STP 21-24 Warrior Skills Level 2-3-4", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/file/d/0B6GE42-kvADvZTY4YjZhMmMtOWNjYy00MDI5LWFhMTItYTkwYjkzZDcwNjE5/edit?pli=1", "title": "Army FM 21-76 Survival Manual", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNGU4ODU0ZGQtMzNjNi00Mjk3LTljNTMtOWFjYzA0OTkzNzgz", "title": "Army FM 31-70 Basic Cold Weather Manual", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMGRhYjQ3MzEtZDBjYi00YWYxLWE1YWUtM2FkMTBjYjQ2YzRj", "title": "Army FM 20-3 Camouflage Concealment and Decoys", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvYWMxYWI1ZjQtNDc3MS00OTA0LThiNzUtNmQxN2JjZmQxODAz", "title": "Army FM 5-103 Survivability", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvN2UwOTQwYWQtNTYwZi00ZjVlLWE5MmMtODAyOTdhYTIyODRl", "title": "Army FM 3-06 Urban Operations", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KMGI5YjAyM2UtNDhhOS00ODNhLWJjZWUtYTIxYjkxN2MyZTEz", "title": "Navy SEAL Physical Fitness Guide", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KZDgzNjNmOWUtM2I2Zi00NWZmLWI3NmMtNzFkZDVmZjYwNWU2", "title": "US Marines Close Quarters Combat Manual", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KZmE5MWI5ZjMtNmZmYy00ZmIxLWFlNjUtY2RlNmJhNjQ3ZTYz", "title": "US Marine Corps Hand to Hand Combat", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KYWE1Mzg0NDUtZmJiNS00NTEwLWJjZjAtMWRkODg1MjZhNDlh", "title": "US Army Combatives FM 3-25.150", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KOWU0ZDA1YmEtMzYwYi00NzJhLThmNTUtNzM4ODJjYTdhZDIx", "title": "Pressure Points Military Hand to Hand Combat Guide", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KMWY2ZDc4MmYtZDk5MC00YmM3LTgyODUtYTRmMWJjNWI1YjQ1", "title": "Practical Unarmed Combat by Moshe Feldenkrais", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KZmRiNGZlMjEtOTI3ZC00MTM1LWE5ZWItN2UzMDA3YTkzODA2", "title": "Krav Maga Pressure Points Guide", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KMzUxYjhmNWUtOTAxOC00OWVlLWJmMjMtMzRjZWJjOGZiM2Rh", "title": "Aikido Revised", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KNGVjOTdjYTctNzNkYi00ZTdlLWE3OGUtZTVlMzNiNDllYWYy", "title": "Combat Conditioning Manual JiuJitsu", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KNzFmMjIzMDEtMDIyNi00NTBhLTk3NDMtOGYwODIxMDRlYmUy", "title": "Marine Martial Arts Training", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvOTk3OTlkNDgtODZkZi00NmQzLWFjMGItMGJmNTdjODYzOTdk", "title": "Combat Survival Evasion", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KM2Q2ZWQ3YmQtMzZhYS00ZWVhLTliYTItNDBiMGY2MzYxNzNm", "title": "USMC Kill or Get Killed", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZDIzM2MxOWUtMDY5NS00OTE2LWFlNGYtOWJjMWQzMmEyMTlj", "title": "Surviving Terrorism", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMjZiZThiNWQtOTdjOC00ZmMwLTk4YzAtMjY2ODFkNWMwYWQz", "title": "Marines Individual Terrorism Survival", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNDFhNTZhZTEtZTlkZS00M2Q1LTkwY2ItZGQ1NjFhYzc2ZDYx", "title": "Nuclear War Survival Skills", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMDczYTY3YmUtNWY0ZC00ZTJiLTk2Y2QtMjBmNWZiZjU4OWI3", "title": "Army FM 5-428 Concrete and Masonry", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMDM0ZDA4YzEtM2I0My00NjlhLWE1YTItMjdlYmNjN2YwZjc1", "title": "Army FM 5-426 Carpentry", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/file/d/0B6GE42-kvADvZWE4M2NjN2EtYjJkMC00YTUyLWE0M2UtZTNiOGFlNzc1Njc1/edit?pli=1", "title": "How to Find Your Way - US Army", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvYzYyNTg4M2ItYzk4Zi00MzU2LWFlNjEtZmNiMjU4ZGE0MWVi", "title": "Urban Preparation Kit Part I On-Body Kit", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvYTUzYjdkYzQtMGRlYS00YmEzLWFhYzYtNTJiOTdhN2EwY2Yw", "title": "Western Australia Police Aids To Survival", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvOWM5OTBiMzgtNzE4Ny00ZTgzLTgzMmMtM2E5ZWY1YzVlZmQw", "title": "USMC Winter Survival Course", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMmIxZGVmMDMtYTRiZC00MjRiLTljNzgtYjA1YTNiMjk3Mzhh", "title": "USMC Summer Survival Course", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvOWE3NWI5MTMtNWViMi00M2UyLWIxY2EtZGE0OTY4MjdkNTYy", "title": "How to Build a Debris Hut", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KZmI0YjA2YzUtZmViNS00YzVmLThkMzktNmJlMzk1YTFiZTc1", "title": "Shelters Shacks Shanties - Daniel Carter Beard", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMjJhNmM4ODEtNmU3Yy00OTJkLWFkMTAtZTU1NzQ2MmE4ZmI1", "title": "Edible Wild Plants", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMDZjZTA1NjAtZTQ2Ni00OWU2LTk2NDItODVlOGY5NzM5YTU2", "title": "Common Edible Mushrooms", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvODhhMTdkNGMtNjEyNy00NDNlLTg2M2MtMzA2ODhhYzNjNGFm", "title": "WHO Monographs on Selected Medicinal Plants Vol 3", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvOTk4MzRkYWYtZTNhNi00OTg0LThlMGYtN2IxYWVmODE5MzY3", "title": "WHO Monographs on Selected Medicinal Plants Vol 2", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvY2RjMDk3ODMtZDFjYi00YmM3LWFkOGMtMTgyODExMmJmYjk1", "title": "WHO Monographs on Selected Medicinal Plants Vol 1", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZjY2NTcyNzktOTIyMy00Y2Y1LTg0MzYtNzUyZGZhMWQ4MTI4", "title": "Useful Wild Plants of the United States and Canada", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZDVkMjQ4MGMtZmJlZC00OGE1LWFlYzItMmYyNjY5NjEwZDA4", "title": "How to Make Herbal Preparations", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMjkyY2MwMzQtMDk5ZC00ZjFjLTg1YzQtZjcyZjJmYzY0OTBm", "title": "Survival Edible Medicinal Plants", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNGNmZGNlZmItMjA1MS00MmU4LWE4YjUtMWZhNjY0M2E3NDNj", "title": "Medicinal Plants in Folk Tradition", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZTRkZmE5NTctM2JiNC00NTExLTgxMWYtYWE0MDg0MzQyYTcz", "title": "Herbal PDR", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNDc2M2Y3ZGMtOGVhZS00OTEwLWJkZDYtY2NjM2I1YTU5MDY0", "title": "Healing Pets With Alternative Medicine", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNmE4MDBmMzAtMDU3NC00NWZiLThhY2QtMmYwNWRmNjZkNWQ0", "title": "Edible and Medicinal Plants", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNDIxNjM2OTgtYzBmYS00ZjI3LWE0MTItODExM2ZkNTk1NmQ2", "title": "Crow Indian Recipes and Herbal Medicines", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvODU0MTMwNGMtN2NhOS00ZjUyLWFlNjEtMmMwMzNmNmQwZmVj", "title": "Anticancer Therapeutics", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvYjEyOTQxM2EtZjBkMi00Njg1LWFjYWEtMmU5ODg0MjRhYzEz", "title": "A Complete Handbook of Nature Cure", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvYzI0YzgyNGMtNGIzNS00MjlkLTg5MDAtNWVmZDY4NmU3MzM4", "title": "WHO Monographs on Selected Medicinal Plants Vol 4", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/file/d/0B6GE42-kvADvMTY3NmZhNGUtN2RmOS00MzA4LThiNTctOGU1MTllODM0Zjlh/edit?pli=1", "title": "Traps and Snares", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNWRlMjMzODAtN2ZhZS00MGZlLWI1MTgtODY4MTBiZDg2ZDhi", "title": "Camp Life in the Woods and Tricks of Trapping", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMjZlODlhMDAtYTM3MS00OWFhLTg3ZWMtZWQ1YWQzNTZmYjU1", "title": "Alpine Living for SAR", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvOWQyNjhhZTItMGMzYS00ZjgyLTliYzgtN2IxYjVlYWE3M2Vi", "title": "Cold Weather Survival Rev 2", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvODM5ZjE1YTAtODkwNC00NTcxLTliNDAtMWRlZmU1MWNjZGJl", "title": "Cold Weather Survival", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvYjQ1MjJmODgtZjVmZS00YTQ4LTk4NGItM2JkZjAwMmYxZDVi", "title": "Survival In Cold Weather Areas", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMjAwNmY0OTctNDA4ZS00ZjI2LWE0MjgtZjhiMTc5NzU1ODFi", "title": "Wilderness Survival Skills", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMGUyOTg4YjctYjM0OC00N2NiLTg0NTAtYWU2OGIzNjI2ZmRl", "title": "Survival Wilderness Survival", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvYjhjMDg5Y2YtMGQ0ZS00NjNjLWExYWItNTE4NmM1ZjNhNDZj", "title": "Adventurer Woodstravel Module", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KN2Q5N2I0NTQtZjE1OS00ZTRiLWIxNDAtMzkxMzU0ODYwMmRk", "title": "Australian Bushcraft", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KNTc3MTcxMzQtZjQ0MS00ODc2LWEzNDUtMzlmMWI5ZDM1NDMy", "title": "Flintknapping", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KYTFlZjA5MjEtYTU1OS00ZTMwLWI2Y2UtOTNhM2EyMGY2Mjcz", "title": "The Book of Camplore and Woodcraft - Dan Beard", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KMGMyNjFhMDgtMzlkNC00NDNlLWJiZmMtZGU2ODhkODY0MjZl", "title": "Bushcraft Scouting Woodlore Notes", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KOGI2MzA1NTAtMGViMC00ODA0LWFlNTgtOTNjODdmNTg4YTNk", "title": "Woodsmanship", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KYjY5MzA0MzctM2UxOS00YmQwLTliNWMtNGFlYzIwYmZmNzQw", "title": "Vegetable Garden Encyclopedia", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMWIyMjUwOTEtMjgyZS00NGZiLTkyMDctNjY1ZjIxNGM3NGM5", "title": "Preserving Game Meats", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KN2IzZjRmNjAtZmU5Mi00M2NiLWE3ZTktYTE3NzQyY2Y5NTQ1", "title": "Guide 5 Preparing and Canning Poultry Red Meats and Seafood", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KOTJlNjM5ZDItY2ZlOS00ZmY0LTlkOTYtNDIxYTA0YzUzNjc0", "title": "The Jerky Chef", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KOThkZTU4NjctMTJhMi00NGE3LTlmN2QtYmZlYzQ4YTkwZTkw", "title": "Solar Dehydrator", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KYzRiYjRhYzUtMTcyMC00NTI5LWJlOWUtZTk5MDcwYmQwNzlm", "title": "Small Scale Food Drying Technologies", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KNzNkNzU0NzAtZWU3NC00NTVlLThhNTMtYTcxYjIzMDA2MTli", "title": "Preserving Food Drying Fruits And Vegetables", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KODViZmYwZDEtOWE0OC00ZGJjLTgxZTItODMyMzllNGYwMzk4", "title": "Guide 6 Preparing and Canning Fermented Foods and Pickled Vegetables", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KYWRkNDgyNjYtZmU1NS00NGRhLTkyZjEtNmY0ODdkZDk4OWU4", "title": "1999 Dutch Oven Cookbook", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KMjMwMmJhNTUtYTYzZC00MzA3LWE3MTYtMWNmZWQ0ZjZlNGU3", "title": "Boy Scout Cookbook", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KOTE3M2U0ZDYtZmQ3NC00NWI4LThiZWItMjZhMzU0MzRiZWY2", "title": "The Back Country Recipe Book", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KMmM5OTk4NzQtYzY4OC00OTFlLWJhOGYtOThmMDEwMzk2M2Mz", "title": "Native Berry Recipes", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KZDNhMmExZmUtNmI3YS00YjBiLWIyNTktOWRhMGExZmYzNTU0", "title": "The Baby Food", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KZjdmNDhkNDMtNTI4MC00ZWM3LWE1MTMtZGE3MzkyNmFmMjg2", "title": "Bushcraft Leather Work", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KODJlMTU3MTItY2MxNS00MTZiLWEyODEtMTU5YWQwZjZmZDFi", "title": "Foxfire One", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KOTU2MjI3NTAtYTNjYS00ZDZhLWI0ZDMtZDNjNjMwMzRiNDM1", "title": "Foxfire Two", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KNzJjOWYxMDUtNjg1ZC00YzRmLWE0NTItYmMzMThhMjlhZmM2", "title": "Foxfire Three", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KMzZhYTE0OTMtNTdjNy00ZWNkLWI2MzQtNDIwMDJhZWZkYTMz", "title": "The Unofficial MacGyver How-To Handbook", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KZmUzNzJmZWYtZTEyZC00YmNhLWI3YjEtZjEyN2VmMTMyMTIw", "title": "The Complete Guide to Home Carpentry", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KY2YzNDNhOTUtMDYzMC00OGUwLTlkNTEtNTdhZTliZWJhZWRm", "title": "Metal Forming", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZmVkYTM3MTQtOWVmMi00YWNjLWE2MjktYTQ0NDAxMzZlMWQ1", "title": "HHS Pandemic Influenza Plan", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZDk0NGM5Y2YtOTUwMS00ZWM3LTgxMWMtNjU5ZWQwNDk5ZjE4", "title": "Where There is No Dentist", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMGE0Nzk5ZjktOWU3MC00ZTkxLWIwZDgtNTk0Yzk0YzVmNzky", "title": "Personal Wilderness Medical Kit", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMmM2ZDA0Y2ItM2NiYS00YzVjLTgyYTAtYWExMmUzNjczZDc1", "title": "Wound Closure Manual", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvYjM2MTVhNjQtMjYwNS00YmU2LTk5MTQtYjRmNWI3NDA4YTRl", "title": "Full First Aid Manual FM 21-11", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNzk4M2ZmNWItMzM1Yi00NDNkLWI2MjItNDQxOGQyNTBlMTNm", "title": "Emergency War Surgery", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZDhmYjA5YzQtOGRhNi00MDkyLTkxZWMtYWYwYjM1YjA3NTc4", "title": "USMC Wilderness Medicine Course", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMThhN2YxMTctNDU4ZS00MGMzLTk2NzgtNmE5YzI5Yzk0ZTky", "title": "Survival Medicine", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KZDU5NWNiMGUtZTUxYy00OTI2LWEyMTAtOWFjYTk4OWQxM2Nm", "title": "Radio Monitoring How-to Guide", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KNzlmZmFhZGEtOWZkYy00NDJlLWI5ZDktM2JlYjhmOGQwMmE5", "title": "Practical Guide to Free Energy Devices", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvODk1YThhZDUtNzEyNC00MDA4LThiNTAtZGY1NDQyNGI2M2Q2", "title": "Survival Water Purification", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/file/d/0B6GE42-kvADvNTk2MDU0MzgtODE0My00ODVjLWJhMTgtOGMyMzhiOWFmZjk1/edit?pli=1", "title": "Knots - Andrew Adamides", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNmE3ODUxNTQtOTAyYi00YjE5LThiYTUtNjkxZTY4Mjk1ZmIz", "title": "Sea Scout Knots", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZjkyOTNlOTItNDUyMi00YjNhLWI3NjgtNzhmYzc0NjZlNzQy", "title": "Ropes Knots Ladders Lashings Anchorages", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZmUxMjUxZDUtODEyZC00OTk5LTlhYTktMDkwNmRiZmM1ZjY4", "title": "Knots Splices Attachments", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvYjhiNzkxYjYtZDZlNy00NWIxLWIxMjMtMmJhNzM0ZDhkMTcx", "title": "Knots Splices and Rope Work", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNjJhMTA4ZGQtYjk3MC00YTUxLWEwOGItMDAxMjYzMTE4NDI5", "title": "Knots for Mountaineering Camping Climbing Utility Rescue", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNTk2MDU0MzgtODE0My00ODVjLWJhMTgtOGMyMzhiOWFmZjk1", "title": "Knots by Andrew Adamides", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvOTBlNDExN2UtODM3Yy00YTg2LWI2NDEtYjFiNDViYjQ4OGQx", "title": "Pioneering Knots and Lashings", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZGY3MDhkMzAtOGQxMC00M2I2LWE1NzItY2Y4NmFjZTFiMmIw", "title": "KNOTS", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvNjZmMDY0NGItZThhZS00OTcyLWJlYTktMjIxYjg2ZDc2NTQ4", "title": "Handbook of Knots and Splices", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMzIzNGQ1MGEtMWQxYi00MWE2LWJiNGEtNTMzOWIwN2I2NDNi", "title": "Fishing Knots Tying How To Tie A Knot", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMDMyMmNiMzctZGIyMC00Yjk5LThmMGUtOTRlOGRjNTBhODQ1", "title": "Essential Fishing Knots", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMzJiZmI2NTktMzM5Ni00MzU4LTg5M2ItMDJiMGI1MmRlNDk4", "title": "Encyclopedia of Knots", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvZDMzZTlmNjAtMjVmMS00NGNkLWI5YTEtMWM1ZTgxYTY3NGZk", "title": "Basic Book of Knots and Lashings", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvMmI3MWM5MWQtNDI1Zi00YjJhLWEwODItZDRkNWNlZWQ0ZGY5", "title": "What Knot - Useful Knots for Scouting and Climbing", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6GE42-kvADvYzNmOGM5OTEtMTRmNy00MTc2LThiNDAtZmExYmE1YWMzMjZj", "title": "Tying Farm Knots", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KMTcyMjQ0NzgtNWQ5YS00YzEzLThmZWUtZTQ0Mjk5YzRmZGIy", "title": "Steal This Book", "source": "scp-gdocs"},
    {"url": "https://docs.google.com/open?id=0B6Swa8Pwy-0KOTMwN2EyNTQtNTAyZC00YTNiLWFkYzUtODg2ZWQyMjUwNThi", "title": "Secret Hiding Places", "source": "scp-gdocs"},
]

# Source: archive.org - Homesteading and Survival Manuals collection
ARCHIVE_ORG_URLS = [
    {"url": "https://archive.org/download/homesteading-survival-manuals/101%20Practical%20Uses%20for%209%20essential%20oils.pdf", "title": "101 Practical Uses for 9 Essential Oils", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/4-h%20Beekeeping.pdf", "title": "4-H Beekeeping", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/5%20Simple%20Rules%20to%20Winning%20Any%20Fight.pdf", "title": "5 Simple Rules to Winning Any Fight", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/65%20Amish%20Recipes.pdf", "title": "65 Amish Recipes", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/A%20Better%20Way%20to%20Gardening.pdf", "title": "A Better Way to Gardening", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Above%20Ground%20Storm%20Shelter.pdf", "title": "Above Ground Storm Shelter", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Acute%20Medicine.pdf", "title": "Acute Medicine", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Aid-to-Survival.pdf", "title": "Aid to Survival", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Army%20FM%2021-150%20-%20Hand%20To%20Hand%20Combat.pdf", "title": "Army FM 21-150 Hand To Hand Combat", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Backcountry%20Cookbook%20PDF.pdf", "title": "Backcountry Cookbook", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Basic%20Herbalism.pdf", "title": "Basic Herbalism", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Basic%20Survival%20Medicine.pdf", "title": "Basic Survival Medicine", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Beginner%20in%20Bee%20Culture.pdf", "title": "Beginner in Bee Culture", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Best%20Way%20To%20Split%20Firewood.pdf", "title": "Best Way To Split Firewood", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Box%20Oven%20Cooking.pdf", "title": "Box Oven Cooking", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Bug%20Out%20Bag.pdf", "title": "Bug Out Bag Guide", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Bug%20Out%20Vehicle%20Basics.pdf", "title": "Bug Out Vehicle Basics", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Build%20A%20Solar%20Hydrogen%20Fuel%20Cell%20System.pdf", "title": "Build A Solar Hydrogen Fuel Cell System", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Build%20Your%20Own%2012vdc%20Engine%20Generator.pdf", "title": "Build Your Own 12V DC Engine Generator", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Bulletproofing%20Homes.pdf", "title": "Bulletproofing Homes", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Canning%20Breads%20and%20Cakes.pdf", "title": "Canning Breads and Cakes", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Canning%20Butter.pdf", "title": "Canning Butter", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Captain%20Dave%27s%20Survival%20Guide.pdf", "title": "Captain Dave's Survival Guide", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Capturing%20Heat.pdf", "title": "Capturing Heat", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Chinese%20Medicine.pdf", "title": "Chinese Medicine", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Coal%20Extenders.pdf", "title": "Coal Extenders", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Coal%20Gasification.pdf", "title": "Coal Gasification", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Combat%20First%20Aid.pdf", "title": "Combat First Aid", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Combat%20Shelters.pdf", "title": "Combat Shelters", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Composting%20Toilet.pdf", "title": "Composting Toilet", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Control%20of%20household%20insects.pdf", "title": "Control of Household Insects", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Cooking%20canning%20cold%20storage.pdf", "title": "Cooking Canning Cold Storage", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Cure%20of%20aneurism%20by%20pressure.pdf", "title": "Cure of Aneurism by Pressure", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Dehydrating%20Food.pdf", "title": "Dehydrating Food", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Desert%20Survival.pdf", "title": "Desert Survival", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Ditch-Medicine-Advanced-Field-Procedures-For-Emergencies-1993.pdf", "title": "Ditch Medicine - Advanced Field Procedures for Emergencies", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/EMERGENCY%20DISINFECTION%20OF%20DRINKING%20WATER.pdf", "title": "Emergency Disinfection of Drinking Water", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Emergency%20Childbirth.pdf", "title": "Emergency Childbirth", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Fighting%20fire.pdf", "title": "Fighting Fire", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Hobo%20Stove.pdf", "title": "Hobo Stove", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Homemade%20Batteries.pdf", "title": "Homemade Batteries", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/How%20To%20Make%20Insect%20Repellant.pdf", "title": "How To Make Insect Repellant", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/How-to-Build-a-Debris-Hut.pdf", "title": "How to Build a Debris Hut", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Human%20Waste%20Sanitation.pdf", "title": "Human Waste Sanitation", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Keeping%20Food%20Safe%20During%20an%20Emergency.pdf", "title": "Keeping Food Safe During an Emergency", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Keeping%20Out%20Rodents..pdf", "title": "Keeping Out Rodents", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/MEDICINAL%20PLANTS.pdf", "title": "Medicinal Plants", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Make%20your%20own%20MREs.pdf", "title": "Make Your Own MREs", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Making%20Charcoal.pdf", "title": "Making Charcoal", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Medical-Survival-Wound-Closure-Manual.pdf", "title": "Medical Survival Wound Closure Manual", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/NATURE%20CURE%20AND%20NATURAL%20METHODS.pdf", "title": "Nature Cure and Natural Methods", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Old%20Laundry%20Manual.pdf", "title": "Old Laundry Manual", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Processing%20Your%20Deer%20at%20Home.pdf", "title": "Processing Your Deer at Home", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Special%20Forces%20Caching%20Techniques.pdf", "title": "Special Forces Caching Techniques", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Surviving%20The%20New%20World%20Order.pdf", "title": "Surviving The New World Order", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/The-Complete-Guide-to-Home-Carpentry.pdf", "title": "The Complete Guide to Home Carpentry", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/The-Making-of-Leather-by-Procter-Makingofleather00procrich.pdf", "title": "The Making of Leather", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/The-New-Complete-Book-of-Food.pdf", "title": "The New Complete Book of Food", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Traps.pdf", "title": "Traps", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/USDA-utah-can-guide-05.pdf", "title": "USDA Utah Canning Guide", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/Using%20A%20Wood%20Cookstove.pdf", "title": "Using A Wood Cookstove", "source": "archive-org"},
    {"url": "https://archive.org/download/homesteading-survival-manuals/survival-personal-wilderness-medical-kit.pdf", "title": "Personal Wilderness Medical Kit", "source": "archive-org"},
]

def get_all_urls():
    """Return combined list of all URLs from all sources."""
    return TRUEPREPPER_URLS + INFOBOOKS_URLS + SCP_DIRECT_URLS + SCP_GDOCS_URLS + ARCHIVE_ORG_URLS
